// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swkupcxotpwtfhpvhzis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3a3VwY3hvdHB3dGZocHZoemlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzA1MjAsImV4cCI6MjA2MTE0NjUyMH0.SrPM47r9oJPjfPMyl62JdyXOZeqECCGcsInYuTekqDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);